"""empty message

Revision ID: e19de121e5da
Revises: c5b7b4e4e52e
Create Date: 2024-09-27 11:04:58.197495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19de121e5da'
down_revision = 'c5b7b4e4e52e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mass', sa.String(length=120), nullable=False),
    sa.Column('hair_color', sa.String(length=120), nullable=False),
    sa.Column('skin_color', sa.String(length=120), nullable=False),
    sa.Column('eye_color', sa.String(length=120), nullable=False),
    sa.Column('birth_year', sa.String(length=120), nullable=False),
    sa.Column('height', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('diameter', sa.String(length=120), nullable=False),
    sa.Column('rotation_period', sa.String(length=120), nullable=False),
    sa.Column('orbital_period', sa.String(length=120), nullable=False),
    sa.Column('gravity', sa.String(length=120), nullable=False),
    sa.Column('population', sa.String(length=120), nullable=False),
    sa.Column('climate', sa.String(length=120), nullable=False),
    sa.Column('terrain', sa.String(length=120), nullable=False),
    sa.Column('surface_water', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Vehicles')
    op.drop_table('Characters')
    op.drop_table('Planets')
    op.drop_table('User')
    op.drop_table('Fave_Vehicles')
    op.drop_table('Fave_chars')
    op.drop_table('Fave_plts')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_constraint('user_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')

    op.create_table('Fave_plts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Fave_plts_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['Planets.id'], name='Fave_plts_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='Fave_plts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Fave_plts_pkey')
    )
    op.create_table('Fave_chars',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Fave_chars_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['Characters.id'], name='Fave_chars_character_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='Fave_chars_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Fave_chars_pkey')
    )
    op.create_table('Fave_Vehicles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Fave_Vehicles_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vehicle_name', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='Fave_Vehicles_user_id_fkey'),
    sa.ForeignKeyConstraint(['vehicle_name'], ['Vehicles.id'], name='Fave_Vehicles_vehicle_name_fkey'),
    sa.PrimaryKeyConstraint('id', name='Fave_Vehicles_pkey')
    )
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"User_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='User_pkey')
    )
    op.create_table('Planets',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Planets_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['Characters.id'], name='Planets_character_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Planets_pkey')
    )
    op.create_table('Characters',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Characters_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('character_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Characters_pkey')
    )
    op.create_table('Vehicles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Vehicles_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('model', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('vehicle_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Vehicles_pkey')
    )
    op.drop_table('favorites')
    op.drop_table('planets')
    op.drop_table('people')
    # ### end Alembic commands ###
